[package]
name = "cargo-debstatus"
version = "0.3.0"
description = "cargo-tree for debian packaging"
authors = ["kpcyrd <git@rxv.cc>",
           "Steven Fackler <sfackler@gmail.com>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/cargo-debstatus"
categories = ["command-line-utilities"]
readme = "README.md"
edition = "2018"

[dependencies]
anyhow = "1.0"
cargo_metadata = "0.14"
petgraph = "0.6"
semver = "1"
serde_json = "1.0"
structopt = "0.3"

colored = "2"
#postgres = { version="0.15.2", features=["with-native-tls"] }
postgres = "0.19"
serde = { version="1.0", features=["derive"] }
dirs = "3"
